### ISSUE TITLE
can I implement this fancy progress bar in pull-to-refresh-listview

### ISSUE THREAD

**Issue by Logan676** [mrwonderman/android-square-progressbar#22]
I have a listview showing a list of files, when use click download all files, I want to use this progressbar to show downloading progress, is it possible for that?

**Comment by mrwonderman** [comment]
As you might saw, this was implemented with the 1.4.1 update. You can use `setImageBitmap(Bitmap bitmap)` method on the square progressbar to set a bitmap.
