### ISSUE TITLE
Indeterminate progress bar

### ISSUE THREAD

**Issue by anticafe** [mrwonderman/android-square-progressbar#26]
Do you have any idea on indeterminate square progressbar? Like the below image.
 
![image](https://cloud.githubusercontent.com/assets/340836/6437731/d2d518bc-c0f4-11e4-8a55-41bc4e076a3d.png)

**Comment by mrwonderman** [comment]
Good Morning,
I haven't implemented this yet. But it sounds very interesting. I will definitely look into it. The only thing I'm not sure about is, how to display the indetermination. Should the progress just go round the image? Do you have any suggestions on how should it be displayed?
Thank you very much for the idea
Yannick

**Comment by anticafe** [comment]
How about mimic [indeterminate animation](http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators) of new Material Design? (Let jump to `Circular` section)

**Comment by mrwonderman** [comment]
That sounds like an ideal way to display it. I looked into it a bit, and the only problem I see so far is, that the implementation would require to fill the progress from lets say 25% done to 50%. Like shown here:

![screen shot 2015-03-06 at 14 36 48](https://cloud.githubusercontent.com/assets/2305653/6526112/6c839e54-c40e-11e4-9ad1-698f50f793ed.png)

At the moment the library has only one possibility to draw a progress. And thats from 0% to a given percentage. So I have to add a new way to do this. But this will also give my the possibility to rewrite some of the big chunk of progress code. I will start working on this today on a new branch.

**Comment by mrwonderman** [comment]
@anticafe Okay, I've kinda got a solution. Sadly I couldn't implement the nice animation mentioned above. But I was really struggling with this implementation. So I will rewrite loads of the onDraw() code for 1.5.0. I made the animation very basic for the moment. Maybe you have some more ideas on how to enhance it. It's just a very hard thing to do, as I'm using the same code as all my other operations on the canvas. This has the advantage that you still can change things like the colour, width and stuff while the "animation" is running.

You can see how it looks on the image beneath, but for a better look, I exported an apk so, you can try it for yourself: https://drive.google.com/file/d/0BwESwPCuXtw7WkxjYjlUYVQ3eTQ/view?usp=sharing

![device-2015-03-08-153207](https://cloud.githubusercontent.com/assets/2305653/6546178/15d0c21a-c5aa-11e4-8b95-5e5b092a41bc.gif)

**Comment by anticafe** [comment]
@mrwonderman Ha ha, the new indeterminate progress bar looks so good :)
I wish you have an extra option to change the default height of progress bar.

**Comment by pasca** [comment]
hi @mrwonderman. Looks good. can push this update for indeterminate progress feature? i download the code on branch indeterminate progress, seem no code changes for that feature.. Thanks!

**Comment by mrwonderman** [comment]
good morning @pasca, yes you're right. I haven't pushed the changes to the branch yet. I will do so at the weekend because I wanna refactor the code a bit. I will comment again, as soon as I did the push. Thanks for bringing this to my attention!

**Comment by tosslife** [comment]
i use android studio IDE, can you  upload this lib on manven  for our ! tanks

**Comment by mrwonderman** [comment]
@tosslife hi, yes I will do so in a few days (I have to create a ticket at sonatype first..). The plan is that I will maintain 2 repositories. One with the current structure as a "legacy repository", so people who still use the eclipse environment don't have to hassle with the new gradle structure. But this repo will be completely migrated to the new android studio (gradle) structure. Locally I already have the repo done. Maybe I can even push it today, I will see.

@pasca I've got the changes done, but as mentioned above, I will migrate first and then push the changes. Sorry for the delay.

**Comment by tosslife** [comment]
@mrwonderman  tanks very much! hope !!!

**Comment by mrwonderman** [comment]
@tosslife hi again, can you text it now? https://github.com/mrwonderman/android-square-progressbar#gradle

**Comment by tosslife** [comment]
@mrwonderman  hi ，error ，theme conflict！！

**Comment by mrwonderman** [comment]
@tosslife try again with the version 1.5.1 please:
```
compile 'ch.halcyon:squareprogressbar:1.5.1'
```

**Comment by tosslife** [comment]
@mrwonderman  tank you ! good

**Comment by mrwonderman** [comment]
@pasca hi, I just pushed the new code concerning the indeterminate feature to the issue_26_indeterminate branch. It will be part of the 1.6.0 release in mid-June. So I will close this issue as soon as that version is published.

**Comment by mrwonderman** [comment]
@pasca, @anticafe 

version 1.6.0 is available now and with it the indeterminate feature [halcyon.ch - squareprogressbar v. 1.6.0](http://halcyon.ch/android-square-progressbar-v-1-6-0/). Thank you very much for your feedback. I will close this issue for now.

**Comment by pasca** [comment]
awesome, thanks for this man. going to use it on my project.

**Comment by anticafe** [comment]
@mrwonderman Thank you again for your hard work :)
