### ISSUE TITLE
layer is breaking and then constructing again at bottom corners.

### ISSUE THREAD

**Issue by topoapp** [mrwonderman/android-square-progressbar#53]
![rightcorner](https://user-images.githubusercontent.com/34789521/37890788-7ea73216-30ef-11e8-857a-5058b2686fe9.png)

![leftcorner](https://user-images.githubusercontent.com/34789521/37890842-a9dfc7b8-30ef-11e8-9092-c1b5a8c85355.png)

while seekbar is being dragged, if we clearly observe there the progress will break and complete again. please check the screenshots at bottom borders.

**Comment by developermanojkumar** [comment]
I too faced the issue. Any solution for it? I need a complete square filling without the image.

**Comment by mrwonderman** [comment]
@topoapp new version with the fix is published (v. 1.6.4). I will, therefore, close this issue now.
